# Dockerfile.react
FROM node:14 AS builder
WORKDIR /app
COPY package.json package-lock.json ./

# Node.js v14에 호환되는 npm 버전 설치 (v6.14.15)
RUN npm install -g npm@6.14.15

# 패키지 설치
RUN npm install

# Install curl
RUN apt-get update && apt-get install -y curl

# Install serve globally
RUN npm install -g serve


COPY . .
RUN npm run build

FROM nginx:1.17.10
COPY --from=builder /app/build /usr/share/nginx/html/react

# Command to run the app
CMD ["serve", "-s", "build"]
