version: "3"

services:
  web:
    build: .
    container_name: dg01
    command: >
      bash -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - ./frontend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "8080:8080"

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react01
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80" # 리액트 개발 서버에서 사용하는 포트는 3000

  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
      - ./frontend/build:/usr/share/nginx/html/react/ # 리액트 정적 파일
    depends_on:
      - web
      - react

  db:
    image: postgres:12.2
    container_name: ps01
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
